version: "3.8"

services:
  postgres:
    image: postgres:14.8-alpine3.18
    restart: unless-stopped	
    environment:
      POSTGRES_DB: loms
      POSTGRES_USER: admin_loms
      POSTGRES_PASSWORD: password 
    ports:
      - "5432:5432"
    volumes:
      - ./loms/migrations:/docker-entrypoint-initdb.d	

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
  
  loms:
    container_name: loms
    restart: unless-stopped
    environment:
      ADDRESS_STORE_LOMS: loms
      DB_CONNECTION: "postgres://admin_loms:password@postgres:5432/loms"
    build:
      context: ./loms
      dockerfile: ./build/Dockerfile
    ports:
      - "50051:50051" # grpc
      - "8085:8085"   # http
    depends_on:
      - postgres

  cart:
    container_name: cart
    restart: unless-stopped
    build:
      context: ./cart
      dockerfile: ./build/Dockerfile
    ports:
      - "8082:8082" # http
    depends_on:
      - loms
