version: "3.8"

volumes:
  prometheus_data: {}
#  grafana_data: {}

services:
  postgres:
    image: postgres:14.8-alpine3.18
    restart: unless-stopped	
    environment:
      POSTGRES_DB: loms
      POSTGRES_USER: admin_loms
      POSTGRES_PASSWORD: password 
    ports:
      - "5432:5432"
    volumes:
      - ./loms/migrations:/docker-entrypoint-initdb.d	
    networks:
        - app-network

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    networks:
        - app-network
  
  loms:
    container_name: loms
    restart: unless-stopped
    environment:
      DB_CONNECTION: "postgres://admin_loms:password@postgres:5432/loms"
    build:
      context: ./loms
      dockerfile: ./build/Dockerfile
    ports:
      - "50051:50051" # grpc
      - "8085:8085"   # http
    depends_on:
      - postgres
    networks:
        - app-network

  cart:
    container_name: cart
    restart: unless-stopped
    environment:
      ADDRESS_STORE_LOMS: loms
    build:
      context: ./cart
      dockerfile: ./build/Dockerfile
    ports:
      - "8082:8082" # http
    depends_on:
      - loms
    networks:
        - app-network

  prometheus:
    image: gitlab-registry.ozon.dev/go/classroom-12/students/homework/prometheus:v2.36.2
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
        - app-network

  jaeger:
    image: gitlab-registry.ozon.dev/go/classroom-12/students/homework/jaegertracing:latest
    ports:
      - "16686:16686"
      - "4318:4318"    
    networks:
        - app-network
        
networks:
  app-network:
    driver: bridge        
